### PR TITLE
fix: Handle Type Error in send-pdf.php

### PR DESCRIPTION
**Pull request by elhaddajiOtmane**

### CODE REVIEW

**Comment by elhaddajiOtmane** [comment]
this is my logfile ```
#1 {main}
  thrown in /var/www/vhosts/mytraitement.com/httpdocs/wp-content/plugins/send-pdf-for-contact-form-7-/classes/send-pdf.php on line 1202
[20-Nov-2023 09:09:51 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /var/www/vhosts/mytraitement.com/httpdocs/wp-content/plugins/send-pdf-for-contact-form-7-/classes/send-pdf.php:1202
```

**Comment by Florent73** [comment]
Hi!

I have adding your code like this:
`if (isset($meta_values['pdf-name']) && is_string($meta_values['pdf-name'])) {
                $singleNamePDF = esc_html(sanitize_title($meta_values['pdf-name']));
            } else {
                // Handle the error or set a default value
                $singleNamePDF = 'document-pdf';
            }`

Thanks

**Comment by elhaddajiOtmane** [comment]
thank u i want to ask please if there is a way to send html in the pdf i want to send html list

Screenshot 2023-11-21 100428
  
i want to send make it like this 
xx

**Comment by Florent73** [comment]
Bonjour,

De façon dynamique ou juste une liste en dur ?

Vous pouvez utiliser n'importe quelle balise HTML pour construire votre PDF.

Cordialement

**Comment by elhaddajiOtmane** [comment]
merci, j'ai utilisé un plugin appelé cf7-conditional-fields pour faire ça

**Pull request closed without merging**
